version: 0.0.1
image_acquisition:
  image_save_dir: 'images'
  camera:
    AcquisitionFrameRate: 30
    ExposureTime: 60000
    OffsetX: 0
    OffsetY: 0
    Width: 1536
    Height: 1536
    PixelFormat: 'BayerRG8'
